New Feature:     -a, add entries to the database from stdin     -as, add passed in entry to the database (skeleton only)

diff --git a/simpledb b/simpledb
--- a/simpledb
+++ b/simpledb
@@ -1,7 +1,9 @@
 #!/bin/bash
 
 # todo
-# -a, add entry to database
+# add type as extension of database file <dname.type>
+# change current to a soft link
+# make -l list types
 # -g, get entry from the database if supported (dict)
 # -r <string>, remove entry if type supports remove (below):
 #	dict, remove by key
@@ -9,8 +11,7 @@
 # make database creation check for database name in archive
 # -ar, archive current database and remove as current
 # -uar <dname>, un-archive database dname
-# -la, list archive database names
-# -ll, list database names and types
+# -la, list archive database names and types
 
 DPATH="/var/simpledb"
 CPATH="config"
@@ -26,6 +27,8 @@ usage() {
 	echo "    -s <dname> - set the database dname to the current database"
 	echo "    -d - delete current database"
 	echo "    -p - print raw text of current database"
+	echo "    -a - add entry to current database from stdin"
+	echo "    -as - add entry to current database from passed in string"
 	exit 0
 }
 
@@ -58,12 +61,20 @@ _delete_current() {
 	fi
 }
 
-_get_current() {
+_get_current_name() {
 	local dname=""
 	if [ -f $DPATH/$CPATH/$CURRENT ]; then
-		local dname=$(head -3 $DPATH/$CPATH/$CURRENT | grep "Name:" | cut -d ' ' -f2)
+		local dname=$(head -3 $DPATH/$CPATH/$CURRENT | grep "name:" | cut -d ' ' -f2)
 	fi
 	echo "$dname"
+}
+
+_get_current_type() {
+	local type=""
+	if [ -f $DPATH/$CPATH/$CURRENT ]; then
+		local type=$(head -3 $DPATH/$CPATH/$CURRENT | grep "type:" | cut -d ' ' -f2)
+	fi
+	echo "$type"
 }
 
 set_db() {
@@ -92,7 +103,6 @@ list_dbs() {
 }
 
 print_db() {
-	echo "$1"
 	dname=$1
 	let x=0
 	while :
@@ -106,6 +116,47 @@ print_db() {
 		fi
 		let "x = $x + 1"
 	done < $DPATH/$dname
+}
+
+_add_entry_to_log() {
+	dname=$1
+	line=$2
+	echo "$DPATH/$dname"
+	echo "$line" >> $DPATH/$dname
+}
+
+_add_entry_to_dict() {
+	dname=$1
+	line=$2
+}
+
+_add_entry_from_stdin() {
+	dname=$1
+	while read line
+	do
+		type=$(_get_current_type)
+		case $type in
+			"log")
+				_add_entry_to_log $dname $line
+				;;
+			"dict")
+				_add_entry_to_dict $dname $line
+				;;
+			*)
+				;;
+		esac
+
+	done < /dev/stdin
+}
+
+add_entry() {
+	dname=$1
+	str=$2
+	if [ "$str" == "_STDIN" ]; then
+		_add_entry_from_stdin $dname
+	else
+		_add_entry_from_string $dname $str
+	fi
 }
 
 while (($#)) 
@@ -139,7 +190,7 @@ do
 			create_db $type $dname
 			;;
 		"-d")
-			dname=$(_get_current)
+			dname=$(_get_current_name)
 			if [ ! -f $DPATH/$dname ]; then
 				echo "database does not exist"
 				exit 5
@@ -162,12 +213,34 @@ do
 			list_dbs
 			;;
 		"-p")
-			dname=$(_get_current)
+			dname=$(_get_current_name)
 			if [ ! -f $DPATH/$dname ]; then
 				echo "database does not exist"
 				exit 7
 			fi
 			print_db $dname
+			;;
+		"-a")
+			dname=$(_get_current_name)
+			if [ ! -f $DPATH/$dname ]; then
+				echo "database does not exist"
+				exit 8
+			fi
+			add_entry $dname "_STDIN"
+			;;
+		"-as")
+			dname=$(_get_current_name)
+			shift
+			entry=$1
+			if [ -z $entry ]; then
+				echo "could not add empty entry"
+				exit 9
+			fi
+			if [ ! -f $DPATH/$dname ]; then
+				echo "database does not exist"
+				exit 10
+			fi
+			add_entry $dname $entry
 			;;
 		*)
 			echo "unknown arg: $1"
